version: 2.1
jobs:
  build:
    docker:
      - image: cimg/node:16.10.0
        auth:
          username: adechauveron
          password: $DOCKER_PASSWORD

    steps:
      - checkout
      - run:
          name: "Hello World"
          command: echo "Hello World"

      - restore_cache:
          keys:
            - npm-v2-dependencies-{{ checksum "yarn.lock" }}
            - npm-v2-dependencies-
      - run:
          name: "yarn install"
          command: yarn install
      - save_cache:
          key: npm-v2-dependencies-{{ checksum "yarn.lock" }}
          paths:
            - node_modules
          
  lint:
    docker:
      - image: cimg/node:16.10.0
        auth:
          username: adechauveron
          password: $DOCKER_PASSWORD
    steps:
      - checkout
      - restore_cache:
          keys:
            - npm-v1-dependencies-{{ checksum "yarn.lock" }}
            - npm-v1-dependencies-
      - run:
          name: "lint step"
          command: |
            yarn lint
            yarn format:check
      - run:
          name: "yarn test"
          command: yarn test

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - lint:
          requires:
            - build
