version: 2.1
jobs:
  build:
    docker:
      - image: cimg/node

    steps:
      - checkout
      - run: echo "Hello World"

      - restore_cache:
          keys:
            - npm-v1-dependencies-{{ checksum "yarn.lock" }}
            - npm-v1-dependencies-
      - run: yarn install
      - run: bundle install --path vendor/bundle
      - save_cache:
          key: npm-v1-dependencies-{{ checksum "yarn.lock" }}
          paths: vendor/bundle
