version: 2.1
jobs:
  build:
    docker:
      - image: cimg/node:16.10.0
        auth:
          username: adechauveron
          password: $DOCKER_PASSWORD

    steps:
      - checkout
      - run:
          name: "Hello World"
          command: echo "Hello World"

      - restore_cache:
          keys:
            - npm-v1-dependencies-{{ checksum "yarn.lock" }}
            - npm-v1-dependencies-
      - run:
          name: "yarn install"
          command: yarn install
      - save_cache:
          key: npm-v1-dependencies-{{ checksum "yarn.lock" }}
          paths: vendor/bundle
